name: checker
on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".doc/**"
      - ".vscode/**"
      - ".gitignore"
      - "README.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - ".doc/**"
      - ".vscode/**"
      - ".gitignore"
      - "README.md"

jobs:
  safe-check:
    runs-on: 'ubuntu-slim'
    steps:
      - name: update package
        run: sudo apt-get update
      
      - name: install luajit
        run: sudo apt-get install luajit -y

      - uses: actions/checkout@v4
      
      - name: run testsuite
        run: luajit testsuite.lua nil nil nil true 0

      - name: run benchmark
        run: luajit benchmark.lua nil nil nil true
  
  loss-check:
    runs-on: 'ubuntu-slim'
    needs: safe-check
    steps:
      - name: update package
        run: sudo apt-get update
      
      - name: install luajit
        run: sudo apt-get install luajit -y
        
      - uses: actions/checkout@v4

      - name: run testsuite as check loss mode
        run: luajit testsuite.lua nil nil nil true 1 2
        