name: checker
on:
  workflow_dispatch:
    inputs:
      use_githubservice:
        description: 'Use GitHub-hosted runner'
        required: true
        type: boolean
        default: false
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  safe-check:
    runs-on: ${{ inputs.use_githubservice == true && 'ubuntu-slim' || 'self-hosted' }}
    steps:
      - name: update package
        run: sudo apt-get update
      
      - name: install luajit
        run: sudo apt-get install luajit -y

      - uses: actions/checkout@v4
      
      - name: run testsuite
        run: luajit testsuite.lua nil nil nil true 0

      - name: run benchmark
        run: luajit benchmark.lua nil nil nil true
  
  loss-check:
    runs-on: ${{ inputs.use_githubservice == true && 'ubuntu-slim' || 'self-hosted' }}
    needs: safe-check
    steps:
      - name: update package
        run: sudo apt-get update
      
      - name: install luajit
        run: sudo apt-get install luajit -y
        
      - uses: actions/checkout@v4

      - name: run testsuite as check loss mode
        run: luajit testsuite.lua nil nil nil true 1 2
        