name: Check & Benchmark module.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: install luajit
        run: sudo apt-get update && sudo apt-get install luajit -y
      
      - name: cleanup
        run: cd .. && rm -rf luajit

      - uses: actions/checkout@v4
      
      - name: run testsuite
        run: luajit testsuite.lua

      - name: run benchmark
        run: luajit benchmark.lua
      
